##
## Build
##
FROM golang:1.16-alpine AS build

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY *.go ./

RUN go build -o /docker-codeedu

CMD [ "/docker-codeedu" ]

##
## Deploy
##
##FROM gcr.io/distroless/base-debian10
##FROM alpine:3.9 
FROM scratch

WORKDIR /

COPY --from=build /docker-codeedu /docker-codeedu

ENTRYPOINT ["/docker-codeedu"]